
package ru.study.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalcWebService", targetNamespace = "http://ws.study.ru/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CalcWebService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.study.ru/CalcWebService/getCalcAddRequest", output = "http://ws.study.ru/CalcWebService/getCalcAddResponse")
    public int getCalcAdd(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.study.ru/CalcWebService/getCalcMultiplyRequest", output = "http://ws.study.ru/CalcWebService/getCalcMultiplyResponse")
    public int getCalcMultiply(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.study.ru/CalcWebService/getCalcSubtractRequest", output = "http://ws.study.ru/CalcWebService/getCalcSubtractResponse")
    public int getCalcSubtract(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.study.ru/CalcWebService/getCalcDivideRequest", output = "http://ws.study.ru/CalcWebService/getCalcDivideResponse")
    public int getCalcDivide(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1);

}
